version: "3.9"

services:
  server:
    build:
      context: .
      target: final
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=db;Database=OnlineStoreDb;User=sa;Password=YourStrong!Passw0rd;Encrypt=False;TrustServerCertificate=True;
      - MongoSettings__ConnectionString=mongodb://mongo:27017
      - MongoSettings__Database=OnlineStoreMongo
      - MongoSettings__ProductChangesCollection=ProductChangeLogs
    depends_on:
      - db
      - mongo

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
      - ./init-db:/docker-entrypoint-initdb.d   # <-- папка з init.sql

  mongo:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
          
volumes:
  sqlserver-data:
  mongo-data: